{
  "id": "CVE-2015-8461",
  "definition_id": "oval:org.opensuse.security:def:20158461",
  "title": "CVE-2015-8461",
  "description": "\n    Race condition in resolver.c in named in ISC BIND 9.9.8 before 9.9.8-P2 and 9.10.3 before 9.10.3-P2 allows remote attackers to cause a denial of service (INSIST assertion failure and daemon exit) via unspecified vectors.\n    ",
  "severity": "Moderate",
  "impact": "moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Tumbleweed"
    ],
    "cpes": [
      "cpe:/o:opensuse:tumbleweed"
    ]
  },
  "packages": [
    {
      "name": "bind",
      "status": "released",
      "fixed_version": "0:9.16.20-1.4",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "bind-doc",
      "status": "released",
      "fixed_version": "0:9.16.20-1.4",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "bind-utils",
      "status": "released",
      "fixed_version": "0:9.16.20-1.4",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "python3-bind",
      "status": "released",
      "fixed_version": "0:9.16.20-1.4",
      "platform": "openSUSE Tumbleweed"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2015-8461",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-8461"
    },
    {
      "id": "SUSE CVE-2015-8461",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2015-8461"
    },
    {
      "id": "SUSE bug 958861",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/958861"
    },
    {
      "id": "SUSE bug 958862",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/958862"
    }
  ],
  "issued": "2021-10-02T00:00:00Z",
  "updated": "2021-10-02T00:00:00Z"
}
