{
  "id": "CVE-2021-37648",
  "definition_id": "oval:org.opensuse.security:def:202137648",
  "title": "CVE-2021-37648",
  "description": "\n    TensorFlow is an end-to-end open source platform for machine learning. In affected versions the code for `tf.raw_ops.SaveV2` does not properly validate the inputs and an attacker can trigger a null pointer dereference. The [implementation](https://github.com/tensorflow/tensorflow/blob/8d72537c6abf5a44103b57b9c2e22c14f5f49698/tensorflow/core/kernels/save_restore_v2_ops.cc) uses `ValidateInputs` to check that the input arguments are valid. This validation would have caught the illegal state represented by the reproducer above. However, the validation uses `OP_REQUIRES` which translates to setting the `Status` object of the current `OpKernelContext` to an error status, followed by an empty `return` statement which just terminates the execution of the function it is present in. However, this does not mean that the kernel execution is finalized: instead, execution continues from the next line in `Compute` that follows the call to `ValidateInputs`. This is equivalent to lacking the validation. We have patched the issue in GitHub commit 9728c60e136912a12d99ca56e106b7cce7af5986. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n    ",
  "severity": "Moderate",
  "impact": "moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Tumbleweed"
    ],
    "cpes": [
      "cpe:/o:opensuse:tumbleweed"
    ]
  },
  "packages": [
    {
      "name": "tensorflow-lite",
      "status": "released",
      "fixed_version": "0:2.9.1-1.1",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "tensorflow-lite-devel",
      "status": "released",
      "fixed_version": "0:2.9.1-1.1",
      "platform": "openSUSE Tumbleweed"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2021-37648",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37648"
    },
    {
      "id": "SUSE CVE-2021-37648",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2021-37648"
    },
    {
      "id": "openSUSE-SU-2022:10014-1",
      "source": "SUSE-SU",
      "url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/U25ZU2T5T4LOLSIYIMGC5PLU4PQQMJE5/"
    },
    {
      "id": "SUSE bug 1189423",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1189423"
    }
  ],
  "issued": "2022-06-30T00:00:00Z",
  "updated": "2022-06-30T00:00:00Z"
}
