{
  "id": "CVE-2019-12781",
  "definition_id": "oval:org.opensuse.security:def:201912781",
  "title": "CVE-2019-12781",
  "description": "\n    An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.\n    ",
  "cvss3": "6.5/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
  "severity": "Moderate",
  "impact": "moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Tumbleweed"
    ],
    "cpes": [
      "cpe:/o:opensuse:tumbleweed"
    ]
  },
  "packages": [
    {
      "name": "python36-Django",
      "status": "released",
      "fixed_version": "0:3.2.7-2.3",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "python38-Django",
      "status": "released",
      "fixed_version": "0:3.2.7-2.3",
      "platform": "openSUSE Tumbleweed"
    },
    {
      "name": "python39-Django",
      "status": "released",
      "fixed_version": "0:3.2.7-2.3",
      "platform": "openSUSE Tumbleweed"
    }
  ],
  "references": [
    {
      "id": "Mitre CVE-2019-12781",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12781"
    },
    {
      "id": "SUSE CVE-2019-12781",
      "source": "SUSE CVE",
      "url": "https://www.suse.com/security/cve/CVE-2019-12781"
    },
    {
      "id": "SUSE-SU-2019:2257-1",
      "source": "SUSE-SU",
      "url": "https://www.suse.com/support/update/announcement/2019/suse-su-20192257-1.html"
    },
    {
      "id": "SUSE-SU-2019:2335-1",
      "source": "SUSE-SU",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2019-September/005894.html"
    },
    {
      "id": "SUSE-SU-2019:2379-1",
      "source": "SUSE-SU",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2019-September/005918.html"
    },
    {
      "id": "SUSE-SU-2019:3127-1",
      "source": "SUSE-SU",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2019-November/006204.html"
    },
    {
      "id": "openSUSE-SU-2019:1839-1",
      "source": "SUSE-SU",
      "url": "https://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html"
    },
    {
      "id": "openSUSE-SU-2019:1872-1",
      "source": "SUSE-SU",
      "url": "https://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html"
    },
    {
      "id": "SUSE bug 1124991",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1124991"
    },
    {
      "id": "SUSE bug 1139945",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1139945"
    }
  ],
  "issued": "2021-10-02T00:00:00Z",
  "updated": "2021-10-02T00:00:00Z"
}
