{
  "id": "CVE-2013-2112",
  "definition_id": "oval:org.opensuse.security:def:20132112",
  "title": "CVE-2013-2112",
  "description": "\n    The svnserve server in Subversion before 1.6.23 and 1.7.x before 1.7.10 allows remote attackers to cause a denial of service (exit) by aborting a connection.\n    ",
  "severity": "Low",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Leap 42.1"
    ]
  },
  "packages": [
    {
      "name": "subversion",
      "status": "released",
      "fixed_version": "0:1.8.10-3.3",
      "platform": "openSUSE Leap 42.1"
    },
    {
      "name": "subversion-devel",
      "status": "released",
      "fixed_version": "0:1.8.10-3.3",
      "platform": "openSUSE Leap 42.1"
    },
    {
      "name": "subversion-perl",
      "status": "released",
      "fixed_version": "0:1.8.10-3.3",
      "platform": "openSUSE Leap 42.1"
    },
    {
      "name": "subversion-python",
      "status": "released",
      "fixed_version": "0:1.8.10-3.3",
      "platform": "openSUSE Leap 42.1"
    },
    {
      "name": "subversion-server",
      "status": "released",
      "fixed_version": "0:1.8.10-3.3",
      "platform": "openSUSE Leap 42.1"
    },
    {
      "name": "subversion-tools",
      "status": "released",
      "fixed_version": "0:1.8.10-3.3",
      "platform": "openSUSE Leap 42.1"
    }
  ],
  "references": [
    {
      "id": "CVE-2013-2112",
      "source": "CVE",
      "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-2112"
    },
    {
      "id": "SUSE bug 821505",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/CVE-2013-2112"
    },
    {
      "id": "SUSE bug 821505",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/CVE-2013-2112"
    }
  ]
}
