{
  "candidate": "CVE-2019-14491",
  "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered\u003ccv::HaarEvaluator\u003e in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
  "ubuntu_description": "It was discovered that OpenCV incorrectly handled certain files. An attaacker could possibly use this issue to cause a denial of service.",
  "priority": "medium",
  "cvss": {
    "nvd": {
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
      "score": 8.2,
      "severity": "HIGH"
    }
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14491",
    "https://github.com/opencv/opencv/compare/33b765d...4a7ca5a",
    "https://github.com/opencv/opencv/compare/371bba8...ddbd10c",
    "https://github.com/opencv/opencv/issues/15125"
  ],
  "public_date": "2019-08-01T17:15:00Z",
  "packages": [
    {
      "name": "opencv",
      "status": "not-affected",
      "note": "4.1.2+dfsg-4ubuntu3",
      "patches": [
        {
          "source": "upstream",
          "text": "https://github.com/opencv/opencv/commit/321c74ccd6077bdea1d47450ca4fe955cb5b6330"
        }
      ]
    }
  ]
}
