{
  "id": "CVE-2014-4616",
  "definition_id": "oval:com.ubuntu.trusty:def:201446160000000",
  "title": "CVE-2014-4616 on Ubuntu 14.04 LTS (trusty) - low.",
  "description": "Array index error in the scanstring function in the _json module in Python 2.7 through 3.5 and simplejson before 2.6.1 allows context-dependent attackers to read arbitrary process memory via a negative index value in the idx argument to the raw_decode function.\n\nUpdate Instructions:\n\nRun `sudo ua fix CVE-2014-4616` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\nidle-python2.7 - 2.7.6-8ubuntu0.2\nlibpython2.7 - 2.7.6-8ubuntu0.2\nlibpython2.7-minimal - 2.7.6-8ubuntu0.2\nlibpython2.7-stdlib - 2.7.6-8ubuntu0.2\nlibpython2.7-testsuite - 2.7.6-8ubuntu0.2\npython2.7 - 2.7.6-8ubuntu0.2\npython2.7-examples - 2.7.6-8ubuntu0.2\npython2.7-minimal - 2.7.6-8ubuntu0.2\nNo subscription required\n\nidle-python3.4 - 3.4.0-2ubuntu1.1\nlibpython3.4 - 3.4.0-2ubuntu1.1\nlibpython3.4-minimal - 3.4.0-2ubuntu1.1\nlibpython3.4-stdlib - 3.4.0-2ubuntu1.1\nlibpython3.4-testsuite - 3.4.0-2ubuntu1.1\npython3.4 - 3.4.0-2ubuntu1.1\npython3.4-examples - 3.4.0-2ubuntu1.1\npython3.4-minimal - 3.4.0-2ubuntu1.1\npython3.4-venv - 3.4.0-2ubuntu1.1\nNo subscription required",
  "note": "",
  "severity": "Low",
  "affected": {
    "family": "unix",
    "platform": "Ubuntu 14.04 LTS"
  },
  "packages": [
    {
      "name": "python2.7",
      "status": "released",
      "fixed_version": "0:2.7.6-8ubuntu0.2",
      "note": "2.7.6-8ubuntu0.2"
    },
    {
      "name": "python3.4",
      "status": "released",
      "fixed_version": "0:3.4.0-2ubuntu1.1",
      "note": "3.4.0-2ubuntu1.1"
    }
  ],
  "references": [
    {
      "id": "CVE-2014-4616",
      "source": "CVE",
      "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-4616"
    },
    {
      "id": "",
      "source": "REF",
      "url": "https://ubuntu.com/security/CVE-2014-4616"
    },
    {
      "id": "",
      "source": "REF",
      "url": "https://ubuntu.com/security/notices/USN-2653-1"
    },
    {
      "id": "",
      "source": "BUG",
      "url": "http://bugs.python.org/issue21529"
    },
    {
      "id": "",
      "source": "BUG",
      "url": "https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1333396"
    },
    {
      "id": "",
      "source": "BUG",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1112285"
    }
  ],
  "public_date": "2014-06-26T00:00:00Z",
  "public_date_at_usn": "2014-06-26T00:00:00Z",
  "assigned_to": "mdeslaur",
  "rights": "Copyright (C) 2014 Canonical Ltd."
}
