{
  "id": "CVE-2016-1517",
  "definition_id": "oval:org.opensuse.security:def:20161517",
  "title": "CVE-2016-1517",
  "description": "\n    OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.\n    ",
  "severity": "Moderate",
  "affected": {
    "family": "unix",
    "platforms": [
      "openSUSE Leap 42.3"
    ]
  },
  "packages": [
    {
      "name": "libopencv-qt56_3",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "libopencv3_1",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "opencv",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "opencv-devel",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "opencv-doc",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "opencv-qt5",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "opencv-qt5-devel",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "opencv-qt5-doc",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "python-opencv",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "python-opencv-qt5",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "python3-opencv",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    },
    {
      "name": "python3-opencv-qt5",
      "status": "released",
      "fixed_version": "0:3.1.0-4.3",
      "platform": "openSUSE Leap 42.3"
    }
  ],
  "references": [
    {
      "id": "CVE-2016-1517",
      "source": "CVE",
      "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1517"
    },
    {
      "id": "SUSE bug 1033150",
      "source": "BUG",
      "url": "https://bugzilla.suse.com/1033150"
    }
  ]
}
